# Generated by Django 2.1 on 2018-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_pages', '0002_auto_20180825_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='access_url',
            field=models.CharField(help_text='The URL at which this page can be accessed. eg: /terms-and-conditions/', max_length=255, unique=True, verbose_name='access URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, help_text='The content to be displayed in the body of this page.', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='The URL to redirect to when this page is accessed.', max_length=255, null=True, verbose_name='redirect URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(choices=[('simple_pages/base.html', 'simple_pages/base.html'), ('simple_pages/default.html', 'simple_pages/default.html'), ('simple_pages/fade.html', 'simple_pages/fade.html'), ('simple_pages/raw.html', 'simple_pages/raw.html')], default='simple_pages/default.html', help_text='The name of the template to use when rendering this page.', max_length=255, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='The title of this page.', max_length=255, verbose_name='title'),
        ),
    ]
